Task 2/add models
Alex808r/TestGuru pull request #2
Opened 2021-09-29 16:43 UTC by Alex808r

Блок заданий № 2

2021-09-30 06:15 UTC, VidgarVii commented on db/migrate/20210929145407_add_tests_title_null_constraint.rb
> +  # end
это мусорные комментарии. Такое надо удалять

2021-09-30 06:15 UTC, VidgarVii commented on db/migrate/20210929145407_add_tests_title_null_constraint.rb
> +  end
как я уже писал в слаке. В этом ДЗ создаётся 5 моделей. Должно быть 5 миграций. 
Сейчас это абсолютно лишняя трата электроэнергии), так как все опции можно задать сразу при создании таблиц.
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2021-09-30 06:15 UTC, VidgarVii commented on db/migrate/20210929102313_create_tests.rb
> +      t.timestamps
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```
так же как создавал связи в уроке по SQL

2021-09-30 06:15 UTC, VidgarVii commented on db/migrate/20210929163733_add_answers_default_value_to_correct.rb
> +end
если ПР содержит миграции, то принято так же в ПР класть актуальную схему БД

2021-09-30 07:32 UTC, Alex808r commented on db/migrate/20210929163733_add_answers_default_value_to_correct.rb
> +end
Как это сделать?

2021-10-01 07:44 UTC, VidgarVii requested changes

2021-10-01 07:44 UTC, VidgarVii commented on app/models/answer.rb
> +  has_one :user
c ассоциациями ты поторопился. По ним будет еще урок и тогда сделашь всё как надо

2021-10-01 07:44 UTC, VidgarVii commented on db/migrate/20210929154622_create_answers.rb
> +
ответ должен принадлежать вопросу

2021-10-01 07:44 UTC, VidgarVii commented on db/migrate/20210929154622_create_answers.rb
> +      t.boolean :correct, default: true
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2021-10-01 07:44 UTC, VidgarVii commented on db/migrate/20210929102313_create_tests.rb
> +
тесту еще нужен автор. Мы с ним будем много работать. Учти что поле должно называться author_id

2021-10-01 16:51 UTC, merged